name: petShop
description: Pet Shop is an e-commerce application for Android built with Flutter (iOS to come soon).

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.5

  #firebase services
  firebase_auth: ">=0.18.0+1 <5.0.0"
  cloud_firestore: ">=0.14.0+1 <5.0.0"
  firebase_messaging: ">=6.0.16 <15.0.0"
  firebase_core: ">=0.5.0 <3.0.0"
  firebase_storage: ">=4.0.0 <12.0.0"

  #google and other stuff
  flutter_launcher_icons: ">=0.7.5 <0.14.0"
  google_fonts: any
  wc_flutter_share: ">=0.2.0 <0.5.0"
  provider:

  #image processing magic
  carousel_slider: ^2.2.1
  image_cropper: ^1.3.0
  image_picker: ">=0.6.7+4 <2.0.0"

  #location and permission handling stuff
  permission_handler: ^3.1.0
  geolocator: ^5.3.2+2
  geolocation: ^1.1.2
  geocoder: ^0.2.1
  location: ">=3.0.2 <6.0.0"
  dio: ">=3.0.9 <6.0.0"

  #unique thingies
  mask_text_input_formatter: ^1.0.7
  uuid: ">=2.2.0 <4.0.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/petshop-footprint-logo-whiteBg.png"
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/cardImages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
